# -*- coding: utf-8 -*-
"""Video/Audio_Reader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WB_z703qIfuotSdKlK-0ADthTUwUiMRV
"""

import vosk
def extract_text_from_vid(vid_path_or_url):
    text = ""

    # Check if the path is a URL
    if vid_path_or_url.startswith('http://') or vid_path_or_url.startswith('https://'):
        # The path is a URL, download the PDF data
        ! youtube-dl https://www.youtube.com/watch?v=CaQUxy_UiGA --extract-audio --audio-format mp4 --output “audio_vid.%(ext)s”
        vid_path = "audio_vid.mp4"

    else:
        # The path is not a URL, assume it's a local file path
        vid_path = vid_path_or_url

    # Extract text from each page
    ! vosk-transcriber -n vosk-model-en-us-0.22 -i audio_vid.mp4 -o transcription.txt
    doc = open("transcription.txt",'r')
    text = doc.read()
    doc.close()

    return text